# Fashion metadata EDA

Exploratory analysis of `data/FashionDataset/train/styles_train.csv` using **pandas** and **DuckDB** for tables, and **Plotly** for charts.

**Targets for bivariate analysis:** `subCategory`, `season`, `gender`, `occasion`  
(`occasion` is the dataset `usage` column: Casual / Sports / Ethnic / Formal / …)

`id` is treated as an identifier and is excluded from comparisons. `productDisplayName` is also excluded (near-unique text, not a feature).

## Setup

In [1]:
from pathlib import Path

from IPython.display import display

import duckdb
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

ROOT = Path.cwd().resolve()
if ROOT.name == "eda":
    ROOT = ROOT.parent

DATA_PATH = ROOT / "data" / "FashionDataset" / "train" / "styles_train.csv"

pd.set_option("display.max_columns", 50)
pd.set_option("display.max_rows", 80)
pd.set_option("display.width", 140)

px.defaults.template = "plotly_white"
px.defaults.color_discrete_sequence = px.colors.qualitative.Set2

print("data:", DATA_PATH)
print("exists:", DATA_PATH.exists())

data: /Users/nhan.ngo/rmit/COSC2753-Project/data/FashionDataset/train/styles_train.csv
exists: True

## Load and clean

Some `productDisplayName` values contain unquoted commas, which pandas reads as extra `Unnamed` columns. Those fragments are folded back into the name, then dropped.

In [ ]:
raw: pd.DataFrame = pd.read_csv(DATA_PATH)
print("raw shape:", raw.shape)
print("raw columns:", list(raw.columns))

df: pd.DataFrame = raw.copy()
unnamed: list[str] = [c for c in df.columns if str(c).startswith("Unnamed")]
for col in unnamed:
    mask: pd.Series = df[col].notna()
    df.loc[mask, "productDisplayName"] = (
        df.loc[mask, "productDisplayName"].fillna("") + df.loc[mask, col].astype(str)
    )
df = df.drop(columns=unnamed)
df = df.rename(columns={"usage": "occasion"})

TARGETS = ["subCategory", "season", "gender", "occasion"]
ID_COLS = ["id"]
TEXT_COLS = ["productDisplayName"]
FEATURE_COLS = [c for c in df.columns if c not in ID_COLS + TEXT_COLS]
COMPARE_COLS = [c for c in FEATURE_COLS if c not in TARGETS]

con: duckdb.DuckDBPyConnection = duckdb.connect()
con.register("styles", df)

print("clean shape:", df.shape)
print("features:", FEATURE_COLS)
print("targets:", TARGETS)
df.head()

raw shape: (38617, 12)
raw columns: ['id', 'gender', 'masterCategory', 'subCategory', 'articleType', 'baseColour', 'season', 'year', 'usage', 'productDisplayName', 'Unnamed: 10', 'Unnamed: 11']
clean shape: (38617, 10)
features: ['gender', 'masterCategory', 'subCategory', 'articleType', 'baseColour', 'season', 'year', 'occasion']
targets: ['subCategory', 'season', 'gender', 'occasion']

     id  gender masterCategory subCategory articleType baseColour  season  year occasion                                productDisplayName
0  1163     Men        Apparel     Topwear     Tshirts       Blue  Summer  2011   Sports  Nike Sahara Team India Fanwear Round Neck Jersey
1  1164     Men        Apparel     Topwear     Tshirts       Blue  Winter  2015   Sports           Nike Men Blue T20 Indian Cricket Jersey
2  1165     Men        Apparel     Topwear     Tshirts       Blue  Summer  2013   Sports               Nike Mean Team India Cricket Jersey
3  1525  Unisex    Accessories        Bags   Backpacks  Navy Blue    Fall  2010   Casual                      Puma Deck Navy Blue Backpack
4  1526  Unisex    Accessories        Bags   Backpacks      Black    Fall  2010   Sports                       Puma Big Cat Backpack Black

## Overview

In [ ]:
overview: pd.DataFrame = con.sql(
    """
    SELECT
        COUNT(*) AS n_rows,
        COUNT(DISTINCT id) AS n_ids,
        COUNT(DISTINCT gender) AS n_gender,
        COUNT(DISTINCT masterCategory) AS n_masterCategory,
        COUNT(DISTINCT subCategory) AS n_subCategory,
        COUNT(DISTINCT articleType) AS n_articleType,
        COUNT(DISTINCT baseColour) AS n_baseColour,
        COUNT(DISTINCT season) AS n_season,
        COUNT(DISTINCT year) AS n_year,
        COUNT(DISTINCT occasion) AS n_occasion
    FROM styles
    """
).df()
display(overview)

schema: pd.DataFrame = pd.DataFrame(
    {
        "column": df.columns,
        "dtype": df.dtypes.astype(str).values,
        "n_unique": [df[c].nunique(dropna=True) for c in df.columns],
        "n_missing": df.isna().sum().values,
        "pct_missing": (100 * df.isna().mean()).round(2).values,
    }
)
schema

   n_rows  n_ids  n_gender  n_masterCategory  n_subCategory  n_articleType  n_baseColour  n_season  n_year  n_occasion
0   38617  38617         5                 7             41            125            46         4      12           8

               column  dtype  n_unique  n_missing  pct_missing
0                  id  int64     38617          0         0.00
1              gender    str         5          0         0.00
2      masterCategory    str         7          0         0.00
3         subCategory    str        41          0         0.00
4         articleType    str       125          0         0.00
5          baseColour    str        46         14         0.04
6              season    str         4         20         0.05
7                year  int64        12          0         0.00
8            occasion    str         8         72         0.19
9  productDisplayName    str     27551          7         0.02

## Missing values

In [7]:
missing: pd.DataFrame = con.sql(
    """
    SELECT column_name, n_missing, ROUND(100.0 * n_missing / n_rows, 2) AS pct_missing
    FROM (
        SELECT
            COUNT(*) AS n_rows,
            COUNT(*) - COUNT(gender) AS gender,
            COUNT(*) - COUNT(masterCategory) AS masterCategory,
            COUNT(*) - COUNT(subCategory) AS subCategory,
            COUNT(*) - COUNT(articleType) AS articleType,
            COUNT(*) - COUNT(baseColour) AS baseColour,
            COUNT(*) - COUNT(season) AS season,
            COUNT(*) - COUNT(year) AS year,
            COUNT(*) - COUNT(occasion) AS occasion,
            COUNT(*) - COUNT(productDisplayName) AS productDisplayName
        FROM styles
    ) s
    UNPIVOT (n_missing FOR column_name IN (
        gender, masterCategory, subCategory, articleType, baseColour,
        season, year, occasion, productDisplayName
    ))
    WHERE n_missing > 0
    ORDER BY n_missing DESC
    """
).df()
display(missing)

fig: go.Figure = px.bar(
    missing,
    x="column_name",
    y="n_missing",
    text="pct_missing",
    title="Missing values by column",
    labels={"column_name": "Column", "n_missing": "Missing rows"},
)
fig.update_traces(texttemplate="%{text}%", textposition="outside")
fig.update_layout(yaxis_title="Missing rows")
fig.show()

          column_name  n_missing  pct_missing
0            occasion         72         0.19
1              season         20         0.05
2          baseColour         14         0.04
3  productDisplayName          7         0.02

## Univariate analysis

Distribution of each metadata field on its own. High-cardinality fields are shown as top-N plus **Other**.

In [8]:
def value_counts_sql(col: str) -> pd.DataFrame:
    return con.sql(
        f"""
        SELECT
            COALESCE(CAST("{col}" AS VARCHAR), 'Missing') AS value,
            COUNT(*) AS n,
            ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 2) AS pct
        FROM styles
        GROUP BY 1
        ORDER BY n DESC
        """
    ).df()


def plot_univariate(col: str, top_n: int | None = None, height: int = 480):
    counts = value_counts_sql(col)
    title = f"{col} distribution"
    if top_n is not None and len(counts) > top_n:
        head = counts.iloc[:top_n].copy()
        other_n = int(counts.iloc[top_n:]["n"].sum())
        other_pct = round(100.0 * other_n / counts["n"].sum(), 2)
        head = pd.concat(
            [head, pd.DataFrame([{"value": "Other", "n": other_n, "pct": other_pct}])],
            ignore_index=True,
        )
        counts = head
        title = f"{col} distribution (top {top_n} + Other)"

    fig = px.bar(
        counts,
        x="n",
        y="value",
        orientation="h",
        text="pct",
        title=title,
        labels={"n": "Count", "value": col},
        height=max(height, 28 * len(counts) + 120),
    )
    fig.update_traces(texttemplate="%{text}%", textposition="outside")
    fig.update_layout(yaxis={"categoryorder": "total ascending"})
    fig.show()
    return counts

In [9]:
print("Low / medium cardinality fields")
for col in ["gender", "masterCategory", "season", "occasion", "year"]:
    display(plot_univariate(col, height=420))

Low / medium cardinality fields

    value      n    pct
0     Men  20918  54.17
1   Women  14160  36.67
2  Unisex   2080   5.39
3    Boys    814   2.11
4   Girls    645   1.67

            value      n    pct
0         Apparel  19147  49.58
1     Accessories   9819  25.43
2        Footwear   8541  22.12
3   Personal Care   1001   2.59
4      Free Items     83   0.21
5  Sporting Goods     25   0.06
6            Home      1   0.00

     value      n    pct
0   Summer  19137  49.56
1     Fall  10512  27.22
2   Winter   7381  19.11
3   Spring   1567   4.06
4  Missing     20   0.05

          value      n    pct
0        Casual  29641  76.76
1        Sports   3940  10.20
2        Ethnic   2570   6.66
3        Formal   2300   5.96
4       Missing     72   0.19
5  Smart Casual     55   0.14
6        Travel     25   0.06
7         Party     13   0.03
8          Home      1   0.00

   value      n    pct
0   2011  13689  35.45
1   2012  13361  34.60
2   2016   5363  13.89
3   2015   2348   6.08
4   2017   1340   3.47
5   2013   1116   2.89
6   2010    805   2.08
7   2018    392   1.02
8   2014    174   0.45
9   2009     20   0.05
10  2008      7   0.02
11  2007      2   0.01

In [10]:
print("High cardinality fields")
for col, top_n in [("subCategory", 20), ("articleType", 20), ("baseColour", 20)]:
    display(plot_univariate(col, top_n=top_n, height=560))

High cardinality fields

                       value      n    pct
0                    Topwear  14409  37.31
1                      Shoes   6752  17.48
2                       Bags   2648   6.86
3                 Bottomwear   2526   6.54
4                    Watches   2252   5.83
5                  Innerwear   1403   3.63
6                    Eyewear   1047   2.71
7                     Sandal    927   2.40
8                  Fragrance    899   2.33
9                 Flip Flops    862   2.23
10                   Wallets    826   2.14
11                     Belts    793   2.05
12                 Jewellery    669   1.73
13                     Socks    626   1.62
14                     Dress    354   0.92
15                  Headwear    284   0.74
16                      Ties    210   0.54
17  Loungewear and Nightwear    202   0.52
18                     Saree    154   0.40
19               Accessories    134   0.35
20                     Other    640   1.66

                    value     n    pct
0                 Tshirts  6781  17.56
1                  Shirts  3089   8.00
2            Casual Shoes  2683   6.95
3                 Watches  2252   5.83
4            Sports Shoes  1991   5.16
5                    Tops  1614   4.18
6                  Kurtas  1556   4.03
7                Handbags  1439   3.73
8                   Heels  1048   2.71
9              Sunglasses  1047   2.71
10                Sandals   865   2.24
11             Flip Flops   863   2.23
12                Wallets   829   2.15
13                  Belts   795   2.06
14              Backpacks   710   1.84
15                 Briefs   668   1.73
16                  Socks   614   1.59
17           Formal Shoes   610   1.58
18                  Jeans   559   1.45
19  Perfume and Body Mist   557   1.44
20                  Other  8047  20.84

        value     n    pct
0       Black  8814  22.82
1       White  4971  12.87
2        Blue  4441  11.50
3       Brown  3001   7.77
4        Grey  2545   6.59
5         Red  2111   5.47
6       Green  1860   4.82
7   Navy Blue  1680   4.35
8        Pink  1422   3.68
9      Purple  1407   3.64
10     Silver   847   2.19
11     Yellow   678   1.76
12      Beige   642   1.66
13       Gold   467   1.21
14     Maroon   465   1.20
15     Orange   445   1.15
16      Olive   344   0.89
17      Cream   315   0.82
18      Steel   268   0.69
19      Multi   230   0.60
20      Other  1664   4.31

## Bivariate analysis

Each target is crossed with every other feature (except `id` / `productDisplayName`).

- **Cramér's V** measures association strength between categoricals (0 = independent, 1 = fully associated).
- Charts use **row-normalized %** so class imbalance in the target does not hide mix differences.
- High-cardinality partners are truncated to top-N + Other.

In [11]:
def ident(col: str) -> str:
    return '"' + col.replace('"', '""') + '"'


def cramers_v(a: pd.Series, b: pd.Series) -> float:
    tab = pd.crosstab(a.fillna("Missing"), b.fillna("Missing")).to_numpy(dtype=float)
    n = tab.sum()
    if n == 0 or tab.shape[0] < 2 or tab.shape[1] < 2:
        return np.nan
    expected = tab.sum(axis=1, keepdims=True) * tab.sum(axis=0, keepdims=True) / n
    with np.errstate(divide="ignore", invalid="ignore"):
        chi2 = np.nansum((tab - expected) ** 2 / np.where(expected == 0, np.nan, expected))
    r, k = tab.shape
    phi2 = chi2 / n
    phi2corr = max(0.0, phi2 - ((k - 1) * (r - 1)) / (n - 1))
    rcorr = r - ((r - 1) ** 2) / (n - 1)
    kcorr = k - ((k - 1) ** 2) / (n - 1)
    denom = min(kcorr - 1, rcorr - 1)
    if denom <= 0:
        return np.nan
    return float(np.sqrt(phi2corr / denom))


def association_matrix(columns: list[str]) -> pd.DataFrame:
    mat = pd.DataFrame(index=columns, columns=columns, dtype=float)
    for i, c1 in enumerate(columns):
        mat.loc[c1, c1] = 1.0
        for c2 in columns[i + 1 :]:
            v = cramers_v(df[c1], df[c2])
            mat.loc[c1, c2] = v
            mat.loc[c2, c1] = v
    return mat


def _sql_in_list(series: pd.Series, top_n: int) -> str:
    values = series.fillna("Missing").astype(str).value_counts().head(top_n).index.tolist()
    return ", ".join("'" + v.replace("'", "''") + "'" for v in values)


def _collapse_expr(col: str, top_n: int) -> str:
    expr = f"COALESCE(CAST({ident(col)} AS VARCHAR), 'Missing')"
    n_unique = int(df[col].nunique(dropna=False))
    if n_unique <= top_n + 1:
        return expr
    return (
        f"CASE WHEN {expr} IN ({_sql_in_list(df[col], top_n)}) "
        f"THEN {expr} ELSE 'Other' END"
    )


def bivariate_table(
    target: str,
    feature: str,
    top_n_target: int = 12,
    top_n_feature: int = 15,
) -> pd.DataFrame:
    t_expr = _collapse_expr(target, top_n_target)
    f_expr = _collapse_expr(feature, top_n_feature)
    counts = con.sql(
        f"""
        SELECT
            {t_expr} AS target,
            {f_expr} AS feature,
            COUNT(*) AS n
        FROM styles
        GROUP BY 1, 2
        """
    ).df()
    totals = counts.groupby("target")["n"].transform("sum")
    counts["pct_within_target"] = (100 * counts["n"] / totals).round(2)
    target_order = (
        counts.groupby("target")["n"].sum().sort_values(ascending=False).index.tolist()
    )
    counts["target"] = pd.Categorical(counts["target"], categories=target_order, ordered=True)
    return counts.sort_values(["target", "n"], ascending=[True, False])


def plot_bivariate(
    target: str,
    feature: str,
    top_n_target: int = 12,
    top_n_feature: int = 15,
    height: int = 520,
):
    counts = bivariate_table(
        target,
        feature,
        top_n_target=top_n_target,
        top_n_feature=top_n_feature,
    )
    v = cramers_v(df[target], df[feature])
    t_unique = int(df[target].nunique(dropna=False))
    f_unique = int(df[feature].nunique(dropna=False))
    extras = []
    if t_unique > top_n_target + 1:
        extras.append(f"top {top_n_target} {target} + Other")
    if f_unique > top_n_feature + 1:
        extras.append(f"top {top_n_feature} {feature} + Other")
    suffix = f"  ·  {'; '.join(extras)}" if extras else ""
    title = f"{target} vs {feature}  ·  Cramér's V = {v:.3f}{suffix}"

    fig_bar = px.bar(
        counts,
        x="target",
        y="pct_within_target",
        color="feature",
        title=title,
        labels={
            "target": target,
            "pct_within_target": "% within target",
            "feature": feature,
        },
        height=height,
        category_orders={"target": list(counts["target"].cat.categories)},
    )
    fig_bar.update_layout(barmode="stack", legend_title=feature, xaxis_tickangle=-30)
    fig_bar.show()

    pivot = (
        counts.pivot(index="feature", columns="target", values="pct_within_target")
        .fillna(0)
        .reindex(columns=list(counts["target"].cat.categories))
    )
    fig_hm = px.imshow(
        pivot,
        aspect="auto",
        color_continuous_scale="Blues",
        title=f"{feature} mix within each {target} (% of target class)",
        labels={"color": "% within target"},
        height=max(420, 26 * len(pivot) + 180),
        text_auto=".1f",
    )
    fig_hm.update_xaxes(tickangle=-30)
    fig_hm.show()
    return counts

In [12]:
assoc = association_matrix(FEATURE_COLS)
fig = px.imshow(
    assoc.round(3),
    text_auto=True,
    aspect="auto",
    color_continuous_scale="Teal",
    zmin=0,
    zmax=1,
    title="Cramér's V between metadata features",
    labels={"color": "Cramér's V"},
    height=620,
)
fig.show()

target_assoc = (
    assoc.loc[TARGETS, [c for c in FEATURE_COLS if c not in TARGETS]]
    .round(3)
    .T
    .sort_values(TARGETS[0], ascending=False)
)
print("Association of each target with other features")
target_assoc

Association of each target with other features

                subCategory  season  gender  occasion
masterCategory        0.999   0.471   0.175     0.434
articleType           0.959   0.563   0.515     0.660
year                  0.408   0.601   0.180     0.137
baseColour            0.161   0.159   0.210     0.153

### Target: `subCategory`

Compared with `gender`, `masterCategory`, `articleType`, `baseColour`, `season`, `year`, `occasion`.

In [13]:
subcat_partners = [c for c in FEATURE_COLS if c != "subCategory"]
print("Cramér's V vs subCategory")
display(
    pd.Series({c: cramers_v(df["subCategory"], df[c]) for c in subcat_partners}, name="cramers_v")
    .sort_values(ascending=False)
    .to_frame()
)

# Hierarchical view: category tree is the strongest structural signal
tree = con.sql(
    """
    SELECT masterCategory, subCategory, COUNT(*) AS n
    FROM styles
    GROUP BY 1, 2
    ORDER BY n DESC
    """
).df()
fig = px.treemap(
    tree,
    path=["masterCategory", "subCategory"],
    values="n",
    title="subCategory nested in masterCategory",
)
fig.show()

for feature in subcat_partners:
    top_n = 12 if df[feature].nunique(dropna=False) > 12 else 30
    display(plot_bivariate("subCategory", feature, top_n_feature=top_n))

Cramér's V vs subCategory

                cramers_v
masterCategory   0.999332
articleType      0.959103
season           0.533078
occasion         0.465527
year             0.408116
gender           0.302810
baseColour       0.161194

        target feature     n  pct_within_target
52     Topwear     Men  8524              59.16
3      Topwear   Women  4851              33.67
45     Topwear    Boys   618               4.29
0      Topwear   Girls   342               2.37
4      Topwear  Unisex    74               0.51
36       Shoes     Men  4267              63.20
25       Shoes   Women  2181              32.30
24       Shoes  Unisex   263               3.90
22       Shoes    Boys    27               0.40
42       Shoes   Girls    14               0.21
18       Other   Women  1647              50.32
50       Other     Men  1212              37.03
16       Other  Unisex   306               9.35
33       Other   Girls    85               2.60
30       Other    Boys    23               0.70
17        Bags   Women  1686              63.67
15        Bags  Unisex   869              32.82
51        Bags     Men    91               3.44
32        Bags   Girls     2               0.08
23  Bottomwear     Men  1348              53.37
37  Bottomwear   Women   929              36.78
11  Bottomwear   Girls   134               5.30
19  Bottomwear    Boys   106               4.20
38  Bottomwear  Unisex     9               0.36
8      Watches     Men  1298              57.64
55     Watches   Women   801              35.57
54     Watches  Unisex   130               5.77
29     Watches   Girls    15               0.67
35     Watches    Boys     8               0.36
56   Innerwear     Men   926              66.00
7    Innerwear   Women   468              33.36
2    Innerwear   Girls     5               0.36
48   Innerwear    Boys     4               0.29
26     Eyewear     Men   588              56.16
41     Eyewear   Women   313              29.89
40     Eyewear  Unisex   143              13.66
14     Eyewear   Girls     2               0.19
21     Eyewear    Boys     1               0.10
53      Sandal     Men   745              80.37
6       Sandal  Unisex    98              10.57
1       Sandal   Girls    39               4.21
5       Sandal   Women    34               3.67
49      Sandal    Boys    11               1.19
12   Fragrance     Men   524              58.29
43   Fragrance   Women   363              40.38
44   Fragrance  Unisex    12               1.33
31  Flip Flops     Men   468              54.29
10  Flip Flops   Women   225              26.10
9   Flip Flops  Unisex   146              16.94
13  Flip Flops    Boys    16               1.86
20  Flip Flops   Girls     7               0.81
39     Wallets     Men   406              49.15
27     Wallets   Women   399              48.31
28     Wallets  Unisex    21               2.54
34       Belts     Men   521              65.70
47       Belts   Women   263              33.17
46       Belts  Unisex     9               1.13

        target         feature      n  pct_within_target
14     Topwear         Apparel  14409             100.00
7        Shoes        Footwear   6752             100.00
11       Other     Accessories   2253              68.84
2        Other         Apparel    809              24.72
3        Other   Personal Care    102               3.12
6        Other      Free Items     83               2.54
1        Other  Sporting Goods     25               0.76
13       Other            Home      1               0.03
10        Bags     Accessories   2648             100.00
4   Bottomwear         Apparel   2526             100.00
5      Watches     Accessories   2252             100.00
16   Innerwear         Apparel   1403             100.00
8      Eyewear     Accessories   1047             100.00
15      Sandal        Footwear    927             100.00
0    Fragrance   Personal Care    899             100.00
12  Flip Flops        Footwear    862             100.00
17     Wallets     Accessories    826             100.00
9        Belts     Accessories    793             100.00

        target       feature     n  pct_within_target
0      Topwear       Tshirts  6780              47.05
16     Topwear        Shirts  3089              21.44
21     Topwear          Tops  1614              11.20
17     Topwear        Kurtas  1556              10.80
1      Topwear         Other  1370               9.51
8        Shoes  Casual Shoes  2683              39.74
7        Shoes  Sports Shoes  1991              29.49
18       Shoes         Heels  1048              15.52
23       Shoes         Other  1028              15.23
12       Shoes       Sandals     2               0.03
14       Other         Other  3271              99.94
5        Other      Handbags     2               0.06
2         Bags      Handbags  1437              54.27
13        Bags         Other  1211              45.73
9   Bottomwear         Other  2526             100.00
19     Watches       Watches  2252             100.00
4    Innerwear         Other  1403             100.00
6      Eyewear    Sunglasses  1047             100.00
15      Sandal       Sandals   863              93.10
3       Sandal         Other    63               6.80
20      Sandal    Flip Flops     1               0.11
22   Fragrance         Other   899             100.00
25  Flip Flops    Flip Flops   862             100.00
24     Wallets         Other   826             100.00
10       Belts         Other   792              99.87
11       Belts       Tshirts     1               0.13

      target    feature     n  pct_within_target
66   Topwear       Blue  2322              16.11
58   Topwear      White  2082              14.45
12   Topwear      Black  1924              13.35
103  Topwear      Other  1610              11.17
87   Topwear      Green  1188               8.24
..       ...        ...   ...                ...
4      Belts  Navy Blue    15               1.89
72     Belts       Pink    13               1.64
154    Belts      Green    13               1.64
63     Belts     Silver     4               0.50
142    Belts     Yellow     3               0.38

[167 rows x 4 columns]

        target  feature     n  pct_within_target
26     Topwear   Summer  8039              55.79
45     Topwear     Fall  6051              41.99
19     Topwear   Winter   223               1.55
37     Topwear   Spring    96               0.67
12       Shoes   Summer  3060              45.32
6        Shoes     Fall  1832              27.13
4        Shoes   Winter  1591              23.56
16       Shoes   Spring   249               3.69
39       Shoes  Missing    20               0.30
1        Other   Summer  2128              65.02
3        Other     Fall   668              20.41
23       Other   Winter   357              10.91
11       Other   Spring   120               3.67
0         Bags   Summer  1329              50.19
24        Bags   Winter   987              37.27
2         Bags     Fall   272              10.27
9         Bags   Spring    60               2.27
46  Bottomwear   Summer  1491              59.03
27  Bottomwear     Fall   919              36.38
32  Bottomwear   Winter    81               3.21
44  Bottomwear   Spring    35               1.39
10     Watches   Winter  2185              97.02
8      Watches   Summer    63               2.80
15     Watches     Fall     3               0.13
25     Watches   Spring     1               0.04
29   Innerwear   Summer  1147              81.75
22   Innerwear   Winter   218              15.54
49   Innerwear     Fall    34               2.42
40   Innerwear   Spring     4               0.29
34     Eyewear   Winter  1013              96.75
48     Eyewear   Summer    31               2.96
31     Eyewear     Fall     3               0.29
28      Sandal   Summer   463              49.95
47      Sandal     Fall   290              31.28
20      Sandal   Winter   129              13.92
38      Sandal   Spring    45               4.85
14   Fragrance   Spring   895              99.56
18   Fragrance   Summer     4               0.44
36  Flip Flops   Summer   420              48.72
41  Flip Flops     Fall   262              30.39
43  Flip Flops   Winter   145              16.82
33  Flip Flops   Spring    35               4.06
13     Wallets   Summer   436              52.78
5      Wallets   Winter   296              35.84
7      Wallets     Fall    84              10.17
17     Wallets   Spring    10               1.21
21       Belts   Summer   526              66.33
30       Belts   Winter   156              19.67
35       Belts     Fall    94              11.85
42       Belts   Spring    17               2.14

     target feature     n  pct_within_target
13  Topwear    2011  8453              58.66
81  Topwear    2012  5233              36.32
5   Topwear    2010   392               2.72
67  Topwear    2013   134               0.93
50  Topwear    2016   133               0.92
..      ...     ...   ...                ...
35    Belts    2016    49               6.18
60    Belts    2013    44               5.55
84    Belts    2014     3               0.38
46    Belts    2010     2               0.25
57    Belts    2008     1               0.13

[101 rows x 4 columns]

        target       feature      n  pct_within_target
13     Topwear        Casual  10450              72.52
42     Topwear        Ethnic   1962              13.62
38     Topwear        Sports   1079               7.49
16     Topwear        Formal    904               6.27
34     Topwear  Smart Casual     10               0.07
21     Topwear       Missing      3               0.02
12     Topwear         Party      1               0.01
0        Shoes        Casual   4134              61.23
47       Shoes        Sports   1972              29.21
2        Shoes        Formal    612               9.06
49       Shoes        Ethnic     17               0.25
58       Shoes  Smart Casual     16               0.24
30       Shoes         Party      1               0.01
26       Other        Casual   2188              66.85
35       Other        Ethnic    443              13.53
28       Other        Formal    349              10.66
32       Other        Sports    238               7.27
52       Other       Missing     45               1.37
7        Other         Party      8               0.24
44       Other  Smart Casual      1               0.03
53       Other          Home      1               0.03
25        Bags        Casual   2524              95.32
31        Bags        Sports     92               3.47
19        Bags        Travel     25               0.94
33        Bags        Ethnic      4               0.15
27        Bags        Formal      2               0.08
8         Bags         Party      1               0.04
48  Bottomwear        Casual   1670              66.11
1   Bottomwear        Sports    462              18.29
51  Bottomwear        Formal    247               9.78
3   Bottomwear        Ethnic    143               5.66
10  Bottomwear  Smart Casual      2               0.08
24  Bottomwear       Missing      2               0.08
41     Watches        Casual   2163              96.05
17     Watches        Sports     49               2.18
29     Watches  Smart Casual     21               0.93
43     Watches        Formal     18               0.80
60     Watches         Party      1               0.04
18   Innerwear        Casual   1382              98.50
40   Innerwear        Sports     19               1.35
22   Innerwear       Missing      2               0.14
50     Eyewear        Casual   1039              99.24
6      Eyewear        Sports      8               0.76
14      Sandal        Casual    901              97.20
39      Sandal        Sports     14               1.51
15      Sandal        Formal      9               0.97
20      Sandal       Missing      2               0.22
36      Sandal  Smart Casual      1               0.11
55   Fragrance        Casual    887              98.67
11   Fragrance       Missing     10               1.11
23   Fragrance         Party      1               0.11
37   Fragrance        Ethnic      1               0.11
9   Flip Flops        Casual    855              99.19
57  Flip Flops        Sports      7               0.81
4      Wallets        Casual    785              95.04
5      Wallets        Formal     30               3.63
56     Wallets       Missing      8               0.97
59     Wallets  Smart Casual      3               0.36
45       Belts        Casual    663              83.61
46       Belts        Formal    129              16.27
54       Belts  Smart Casual      1               0.13

### Target: `season`

Compared with `gender`, `masterCategory`, `subCategory`, `articleType`, `baseColour`, `year`, `occasion`.

In [14]:
season_partners = [c for c in FEATURE_COLS if c != "season"]
print("Cramér's V vs season")
display(
    pd.Series({c: cramers_v(df["season"], df[c]) for c in season_partners}, name="cramers_v")
    .sort_values(ascending=False)
    .to_frame()
)

for feature in season_partners:
    top_n = 12 if df[feature].nunique(dropna=False) > 12 else 30
    display(plot_bivariate("season", feature, top_n_feature=top_n))

Cramér's V vs season

                cramers_v
year             0.600964
articleType      0.563325
subCategory      0.533078
masterCategory   0.470964
baseColour       0.158953
occasion         0.135154
gender           0.111958

     target feature      n  pct_within_target
7    Summer     Men  10082              52.68
4    Summer   Women   6961              36.37
2    Summer  Unisex    892               4.66
6    Summer    Boys    675               3.53
16   Summer   Girls    527               2.75
20     Fall     Men   6942              66.04
12     Fall   Women   2881              27.41
11     Fall  Unisex    495               4.71
18     Fall    Boys    113               1.07
13     Fall   Girls     81               0.77
22   Winter   Women   3725              50.47
10   Winter     Men   3010              40.78
21   Winter  Unisex    592               8.02
5    Winter   Girls     34               0.46
17   Winter    Boys     20               0.27
3    Spring     Men    877              55.97
9    Spring   Women    586              37.40
8    Spring  Unisex     95               6.06
14   Spring    Boys      6               0.38
19   Spring   Girls      3               0.19
0   Missing   Women      7              35.00
15  Missing     Men      7              35.00
1   Missing  Unisex      6              30.00

     target         feature      n  pct_within_target
8    Summer         Apparel  11296              59.03
9    Summer        Footwear   3943              20.60
3    Summer     Accessories   3840              20.07
17   Summer      Free Items     42               0.22
15   Summer  Sporting Goods     12               0.06
10   Summer   Personal Care      4               0.02
18     Fall         Apparel   7147              67.99
19     Fall        Footwear   2384              22.68
11     Fall     Accessories    969               9.22
16     Fall  Sporting Goods     11               0.10
12     Fall            Home      1               0.01
13   Winter     Accessories   4906              66.47
2    Winter        Footwear   1865              25.27
1    Winter         Apparel    567               7.68
0    Winter      Free Items     41               0.56
7    Winter  Sporting Goods      2               0.03
6    Spring   Personal Care    997              63.62
4    Spring        Footwear    329              21.00
5    Spring         Apparel    137               8.74
20   Spring     Accessories    104               6.64
14  Missing        Footwear     20             100.00

     target     feature     n  pct_within_target
44   Summer     Topwear  8039              42.01
3    Summer       Shoes  3060              15.99
19   Summer       Other  2128              11.12
31   Summer  Bottomwear  1491               7.79
42   Summer        Bags  1329               6.94
25   Summer   Innerwear  1147               5.99
47   Summer       Belts   526               2.75
49   Summer      Sandal   463               2.42
28   Summer     Wallets   436               2.28
22   Summer  Flip Flops   420               2.19
21   Summer     Watches    63               0.33
26   Summer     Eyewear    31               0.16
16   Summer   Fragrance     4               0.02
30     Fall     Topwear  6051              57.56
6      Fall       Shoes  1832              17.43
45     Fall  Bottomwear   919               8.74
13     Fall       Other   668               6.35
43     Fall      Sandal   290               2.76
48     Fall        Bags   272               2.59
37     Fall  Flip Flops   262               2.49
33     Fall       Belts    94               0.89
11     Fall     Wallets    84               0.80
35     Fall   Innerwear    34               0.32
15     Fall     Watches     3               0.03
36     Fall     Eyewear     3               0.03
39   Winter     Watches  2185              29.60
46   Winter       Shoes  1591              21.56
10   Winter     Eyewear  1013              13.72
18   Winter        Bags   987              13.37
38   Winter       Other   357               4.84
34   Winter     Wallets   296               4.01
2    Winter     Topwear   223               3.02
12   Winter   Innerwear   218               2.95
5    Winter       Belts   156               2.11
14   Winter  Flip Flops   145               1.96
1    Winter      Sandal   129               1.75
8    Winter  Bottomwear    81               1.10
41   Spring   Fragrance   895              57.12
32   Spring       Shoes   249              15.89
23   Spring       Other   120               7.66
7    Spring     Topwear    96               6.13
0    Spring        Bags    60               3.83
17   Spring      Sandal    45               2.87
4    Spring  Bottomwear    35               2.23
20   Spring  Flip Flops    35               2.23
9    Spring       Belts    17               1.08
27   Spring     Wallets    10               0.64
29   Spring   Innerwear     4               0.26
24   Spring     Watches     1               0.06
40  Missing       Shoes    20             100.00

     target       feature     n  pct_within_target
35   Summer         Other  7286              38.07
34   Summer       Tshirts  4114              21.50
43   Summer  Casual Shoes  1331               6.96
1    Summer        Shirts  1258               6.57
41   Summer  Sports Shoes  1169               6.11
30   Summer          Tops  1164               6.08
3    Summer        Kurtas   946               4.94
11   Summer      Handbags   713               3.73
2    Summer       Sandals   436               2.28
44   Summer    Flip Flops   420               2.19
33   Summer         Heels   206               1.08
40   Summer       Watches    63               0.33
28   Summer    Sunglasses    31               0.16
9      Fall         Other  3043              28.95
10     Fall       Tshirts  2498              23.76
7      Fall        Shirts  1737              16.52
23     Fall  Casual Shoes   835               7.94
22     Fall  Sports Shoes   701               6.67
8      Fall        Kurtas   608               5.78
49     Fall          Tops   424               4.03
5      Fall       Sandals   270               2.57
25     Fall    Flip Flops   263               2.50
39     Fall      Handbags    80               0.76
16     Fall         Heels    47               0.45
15     Fall       Watches     3               0.03
17     Fall    Sunglasses     3               0.03
27   Winter       Watches  2185              29.60
24   Winter         Other  1892              25.63
18   Winter    Sunglasses  1013              13.72
4    Winter         Heels   762              10.32
46   Winter      Handbags   636               8.62
12   Winter  Casual Shoes   418               5.66
13   Winter    Flip Flops   145               1.96
31   Winter       Sandals   120               1.63
21   Winter       Tshirts   100               1.35
29   Winter        Shirts    72               0.98
0    Winter          Tops    24               0.33
14   Winter  Sports Shoes    12               0.16
32   Winter        Kurtas     2               0.03
45   Spring         Other  1168              74.54
37   Spring  Casual Shoes    99               6.32
36   Spring  Sports Shoes    89               5.68
42   Spring       Tshirts    69               4.40
48   Spring       Sandals    39               2.49
38   Spring    Flip Flops    35               2.23
20   Spring         Heels    33               2.11
50   Spring        Shirts    22               1.40
26   Spring      Handbags    10               0.64
6    Spring          Tops     2               0.13
47   Spring       Watches     1               0.06
19  Missing  Sports Shoes    20             100.00

     target    feature     n  pct_within_target
30   Summer      Black  4067              21.25
15   Summer      White  2578              13.47
58   Summer      Other  2467              12.89
10   Summer       Blue  2289              11.96
26   Summer       Grey  1279               6.68
2    Summer      Brown  1254               6.55
32   Summer        Red  1132               5.92
20   Summer      Green   976               5.10
46   Summer  Navy Blue   951               4.97
31   Summer       Pink   780               4.08
52   Summer     Purple   652               3.41
55   Summer     Yellow   422               2.21
53   Summer     Silver   290               1.52
48     Fall      Black  2168              20.62
14     Fall       Blue  1500              14.27
11     Fall      White  1435              13.65
45     Fall      Other   977               9.29
54     Fall       Grey   861               8.19
49     Fall        Red   652               6.20
41     Fall      Brown   625               5.95
37     Fall      Green   611               5.81
57     Fall  Navy Blue   569               5.41
29     Fall     Purple   515               4.90
50     Fall       Pink   324               3.08
27     Fall     Yellow   173               1.65
33     Fall     Silver   102               0.97
3    Winter      Black  2247              30.44
8    Winter      Other  1186              16.07
34   Winter      Brown  1006              13.63
22   Winter      White   760              10.30
36   Winter       Blue   446               6.04
44   Winter     Silver   391               5.30
18   Winter       Grey   317               4.29
4    Winter        Red   238               3.22
5    Winter       Pink   229               3.10
43   Winter     Purple   196               2.66
16   Winter      Green   189               2.56
0    Winter  Navy Blue   115               1.56
24   Winter     Yellow    61               0.83
39   Spring      Black   328              20.93
1    Spring      Other   209              13.34
21   Spring       Blue   202              12.89
38   Spring      White   197              12.57
51   Spring      Brown   116               7.40
42   Spring       Pink    89               5.68
40   Spring        Red    88               5.62
12   Spring      Green    83               5.30
23   Spring       Grey    83               5.30
7    Spring     Silver    64               4.08
9    Spring  Navy Blue    45               2.87
6    Spring     Purple    42               2.68
19   Spring     Yellow    21               1.34
13  Missing       Grey     5              25.00
28  Missing       Blue     4              20.00
59  Missing      Black     4              20.00
47  Missing     Purple     2              10.00
17  Missing     Yellow     1               5.00
25  Missing      Green     1               5.00
35  Missing      Other     1               5.00
56  Missing      White     1               5.00
60  Missing        Red     1               5.00

     target feature      n  pct_within_target
22   Summer    2012  11423              59.69
31   Summer    2011   4683              24.47
0    Summer    2016   1570               8.20
24   Summer    2013    648               3.39
14   Summer    2017    337               1.76
37   Summer    2015    247               1.29
8    Summer    2010     94               0.49
36   Summer    2014     86               0.45
6    Summer    2018     46               0.24
41   Summer    2008      2               0.01
10   Summer    2009      1               0.01
29     Fall    2011   8749              83.23
40     Fall    2012    964               9.17
11     Fall    2010    638               6.07
39     Fall    2013     66               0.63
3      Fall    2014     30               0.29
2      Fall    2015     28               0.27
12     Fall    2009     19               0.18
38     Fall    2016     11               0.10
17     Fall    2018      6               0.06
23     Fall    2008      1               0.01
33   Winter    2016   3782              51.24
28   Winter    2015   2071              28.06
25   Winter    2012    862              11.68
13   Winter    2018    339               4.59
1    Winter    2011    157               2.13
15   Winter    2010     70               0.95
19   Winter    2013     49               0.66
30   Winter    2014     45               0.61
7    Winter    2017      5               0.07
21   Winter    2008      1               0.01
16   Spring    2017    998              63.69
27   Spring    2013    353              22.53
20   Spring    2012    112               7.15
35   Spring    2011     80               5.11
32   Spring    2014     13               0.83
5    Spring    2010      3               0.19
26   Spring    2008      3               0.19
4    Spring    2007      2               0.13
34   Spring    2015      2               0.13
9    Spring    2018      1               0.06
18  Missing    2011     20             100.00

     target       feature      n  pct_within_target
2    Summer        Casual  14351              74.99
25   Summer        Sports   2081              10.87
27   Summer        Ethnic   1612               8.42
4    Summer        Formal   1048               5.48
14   Summer       Missing     19               0.10
30   Summer        Travel     11               0.06
19   Summer  Smart Casual      9               0.05
24   Summer         Party      6               0.03
9      Fall        Casual   7037              66.94
16     Fall        Sports   1617              15.38
10     Fall        Formal    970               9.23
20     Fall        Ethnic    862               8.20
28     Fall  Smart Casual     13               0.12
31     Fall       Missing     11               0.10
7      Fall         Party      1               0.01
32     Fall          Home      1               0.01
17   Winter        Casual   6882              93.24
18   Winter        Formal    245               3.32
8    Winter        Sports    113               1.53
11   Winter        Ethnic     92               1.25
6    Winter  Smart Casual     30               0.41
0    Winter        Travel     12               0.16
15   Winter         Party      4               0.05
21   Winter       Missing      3               0.04
26   Spring        Casual   1371              87.49
3    Spring        Sports    109               6.96
1    Spring       Missing     39               2.49
29   Spring        Formal     37               2.36
5    Spring        Ethnic      4               0.26
12   Spring  Smart Casual      3               0.19
13   Spring         Party      2               0.13
22   Spring        Travel      2               0.13
23  Missing        Sports     20             100.00

### Target: `gender`

Compared with `masterCategory`, `subCategory`, `articleType`, `baseColour`, `season`, `year`, `occasion`.

In [15]:
gender_partners = [c for c in FEATURE_COLS if c != "gender"]
print("Cramér's V vs gender")
display(
    pd.Series({c: cramers_v(df["gender"], df[c]) for c in gender_partners}, name="cramers_v")
    .sort_values(ascending=False)
    .to_frame()
)

for feature in gender_partners:
    top_n = 12 if df[feature].nunique(dropna=False) > 12 else 30
    display(plot_bivariate("gender", feature, top_n_feature=top_n))

Cramér's V vs gender

                cramers_v
articleType      0.514933
subCategory      0.302810
baseColour       0.209929
occasion         0.207088
year             0.179699
masterCategory   0.174540
season           0.111958

    target         feature      n  pct_within_target
2      Men         Apparel  10875              51.99
3      Men        Footwear   5480              26.20
6      Men     Accessories   3994              19.09
5      Men   Personal Care    527               2.52
13     Men      Free Items     42               0.20
19   Women         Apparel   6886              48.63
7    Women     Accessories   4334              30.61
20   Women        Footwear   2440              17.23
21   Women   Personal Care    462               3.26
8    Women      Free Items     38               0.27
1   Unisex     Accessories   1447              69.57
12  Unisex        Footwear    507              24.38
11  Unisex         Apparel     85               4.09
15  Unisex  Sporting Goods     25               1.20
14  Unisex   Personal Care     12               0.58
4   Unisex      Free Items      3               0.14
18  Unisex            Home      1               0.05
9     Boys         Apparel    743              91.28
10    Boys        Footwear     54               6.63
22    Boys     Accessories     17               2.09
16   Girls         Apparel    558              86.51
17   Girls        Footwear     60               9.30
0    Girls     Accessories     27               4.19

    target     feature     n  pct_within_target
11     Men     Topwear  8524              40.75
47     Men       Shoes  4267              20.40
22     Men  Bottomwear  1348               6.44
33     Men     Watches  1298               6.21
31     Men       Other  1212               5.79
45     Men   Innerwear   926               4.43
36     Men      Sandal   745               3.56
44     Men     Eyewear   588               2.81
5      Men   Fragrance   524               2.51
13     Men       Belts   521               2.49
19     Men  Flip Flops   468               2.24
29     Men     Wallets   406               1.94
39     Men        Bags    91               0.44
0    Women     Topwear  4851              34.26
23   Women       Shoes  2181              15.40
49   Women        Bags  1686              11.91
18   Women       Other  1647              11.63
48   Women  Bottomwear   929               6.56
20   Women     Watches   801               5.66
28   Women   Innerwear   468               3.31
46   Women     Wallets   399               2.82
52   Women   Fragrance   363               2.56
30   Women     Eyewear   313               2.21
2    Women       Belts   263               1.86
32   Women  Flip Flops   225               1.59
17   Women      Sandal    34               0.24
12  Unisex        Bags   869              41.78
26  Unisex       Other   306              14.71
15  Unisex       Shoes   263              12.64
43  Unisex  Flip Flops   146               7.02
21  Unisex     Eyewear   143               6.88
27  Unisex     Watches   130               6.25
25  Unisex      Sandal    98               4.71
38  Unisex     Topwear    74               3.56
34  Unisex     Wallets    21               1.01
9   Unisex   Fragrance    12               0.58
35  Unisex  Bottomwear     9               0.43
42  Unisex       Belts     9               0.43
16    Boys     Topwear   618              75.92
50    Boys  Bottomwear   106              13.02
41    Boys       Shoes    27               3.32
54    Boys       Other    23               2.83
10    Boys  Flip Flops    16               1.97
3     Boys      Sandal    11               1.35
53    Boys     Watches     8               0.98
7     Boys   Innerwear     4               0.49
8     Boys     Eyewear     1               0.12
24   Girls     Topwear   342              53.02
14   Girls  Bottomwear   134              20.78
4    Girls       Other    85              13.18
40   Girls      Sandal    39               6.05
6    Girls     Watches    15               2.33
1    Girls       Shoes    14               2.17
51   Girls  Flip Flops     7               1.09
55   Girls   Innerwear     5               0.78
37   Girls        Bags     2               0.31
56   Girls     Eyewear     2               0.31

    target       feature     n  pct_within_target
35     Men         Other  6305              30.14
34     Men       Tshirts  5085              24.31
1      Men        Shirts  2735              13.07
21     Men  Casual Shoes  2106              10.07
20     Men  Sports Shoes  1548               7.40
39     Men       Watches  1298               6.21
0      Men       Sandals   717               3.43
53     Men    Sunglasses   588               2.81
24     Men    Flip Flops   468               2.24
2      Men        Kurtas    61               0.29
14     Men      Handbags     5               0.02
33     Men          Tops     1               0.00
46     Men         Heels     1               0.00
23   Women         Other  5525              39.02
18   Women        Kurtas  1490              10.52
30   Women          Tops  1386               9.79
26   Women      Handbags  1375               9.71
3    Women         Heels  1047               7.39
22   Women       Tshirts  1003               7.08
25   Women       Watches   801               5.66
36   Women  Sports Shoes   397               2.80
37   Women  Casual Shoes   319               2.25
10   Women    Sunglasses   313               2.21
16   Women        Shirts   275               1.94
38   Women    Flip Flops   225               1.59
19   Women       Sandals     4               0.03
50  Unisex         Other  1173              56.39
7   Unisex  Casual Shoes   220              10.58
9   Unisex    Flip Flops   147               7.07
40  Unisex    Sunglasses   143               6.88
52  Unisex       Watches   130               6.25
11  Unisex       Sandals    94               4.52
51  Unisex       Tshirts    71               3.41
41  Unisex      Handbags    59               2.84
8   Unisex  Sports Shoes    43               2.07
5     Boys       Tshirts   516              63.39
4     Boys         Other   152              18.67
47    Boys        Shirts    78               9.58
43    Boys  Casual Shoes    24               2.95
44    Boys    Flip Flops    16               1.97
49    Boys       Sandals    11               1.35
6     Boys       Watches     8               0.98
48    Boys        Kurtas     5               0.61
42    Boys  Sports Shoes     3               0.37
29    Boys    Sunglasses     1               0.12
12   Girls         Other   234              36.28
17   Girls          Tops   227              35.19
13   Girls       Tshirts   106              16.43
32   Girls       Sandals    39               6.05
15   Girls       Watches    15               2.33
27   Girls  Casual Shoes    14               2.17
28   Girls    Flip Flops     7               1.09
45   Girls    Sunglasses     2               0.31
31   Girls        Shirts     1               0.16

    target    feature     n  pct_within_target
32     Men      Black  5555              26.56
52     Men      White  2941              14.06
42     Men       Blue  2542              12.15
15     Men      Other  1942               9.28
25     Men      Brown  1837               8.78
49     Men       Grey  1724               8.24
11     Men  Navy Blue  1234               5.90
33     Men        Red  1107               5.29
9      Men      Green   872               4.17
58     Men     Purple   511               2.44
30     Men     Yellow   282               1.35
57     Men     Silver   232               1.11
35     Men       Pink   139               0.66
38   Women      Other  2642              18.66
1    Women      Black  2393              16.90
17   Women      White  1638              11.57
8    Women       Blue  1389               9.81
2    Women       Pink  1058               7.47
59   Women      Brown  1025               7.24
26   Women     Purple   816               5.76
45   Women      Green   749               5.29
3    Women        Red   674               4.76
6    Women       Grey   645               4.56
27   Women     Silver   603               4.26
40   Women  Navy Blue   282               1.99
23   Women     Yellow   246               1.74
43  Unisex      Black   742              35.67
34  Unisex       Blue   255              12.26
46  Unisex        Red   188               9.04
50  Unisex      Other   156               7.50
14  Unisex       Grey   139               6.68
56  Unisex      White   132               6.35
18  Unisex      Brown   126               6.06
0   Unisex      Green   115               5.53
29  Unisex  Navy Blue    87               4.18
44  Unisex       Pink    51               2.45
53  Unisex     Purple    48               2.31
12  Unisex     Yellow    32               1.54
55  Unisex     Silver     9               0.43
28    Boys       Blue   156              19.16
4     Boys      White   152              18.67
19    Boys        Red   106              13.02
39    Boys     Yellow    88              10.81
21    Boys      Black    83              10.20
63    Boys      Green    81               9.95
7     Boys  Navy Blue    52               6.39
24    Boys      Other    42               5.16
41    Boys       Grey    31               3.81
48    Boys      Brown    10               1.23
22    Boys       Pink     9               1.11
10    Boys     Purple     4               0.49
61   Girls       Pink   165              25.58
47   Girls      White   108              16.74
54   Girls       Blue    99              15.35
13   Girls      Other    58               8.99
20   Girls      Green    43               6.67
60   Girls      Black    41               6.36
62   Girls        Red    36               5.58
51   Girls     Yellow    30               4.65
36   Girls     Purple    28               4.34
16   Girls  Navy Blue    25               3.88
31   Girls       Grey     6               0.93
5    Girls      Brown     3               0.47
37   Girls     Silver     3               0.47

    target  feature      n  pct_within_target
5      Men   Summer  10082              48.20
11     Men     Fall   6942              33.19
14     Men   Winter   3010              14.39
2      Men   Spring    877               4.19
18     Men  Missing      7               0.03
4    Women   Summer   6961              49.16
12   Women   Winter   3725              26.31
19   Women     Fall   2881              20.35
16   Women   Spring    586               4.14
21   Women  Missing      7               0.05
15  Unisex   Summer    892              42.88
6   Unisex   Winter    592              28.46
8   Unisex     Fall    495              23.80
0   Unisex   Spring     95               4.57
9   Unisex  Missing      6               0.29
3     Boys   Summer    675              82.92
22    Boys     Fall    113              13.88
1     Boys   Winter     20               2.46
7     Boys   Spring      6               0.74
20   Girls   Summer    527              81.71
10   Girls     Fall     81              12.56
17   Girls   Winter     34               5.27
13   Girls   Spring      3               0.47

    target feature     n  pct_within_target
3      Men    2011  9015              43.10
27     Men    2012  5789              27.67
34     Men    2016  3452              16.50
0      Men    2013   720               3.44
32     Men    2017   616               2.94
41     Men    2010   563               2.69
24     Men    2018   356               1.70
17     Men    2015   312               1.49
20     Men    2014    72               0.34
42     Men    2009    16               0.08
40     Men    2008     5               0.02
13     Men    2007     2               0.01
8    Women    2012  5924              41.84
19   Women    2011  3614              25.52
4    Women    2015  1757              12.41
10   Women    2016  1583              11.18
22   Women    2017   700               4.94
15   Women    2013   274               1.94
23   Women    2010   183               1.29
5    Women    2014    94               0.66
43   Women    2018    28               0.20
25   Women    2009     3               0.02
7   Unisex    2011   751              36.11
18  Unisex    2012   542              26.06
38  Unisex    2016   305              14.66
28  Unisex    2015   278              13.37
26  Unisex    2013   106               5.10
14  Unisex    2010    57               2.74
36  Unisex    2017    24               1.15
1   Unisex    2018     8               0.38
29  Unisex    2014     8               0.38
16  Unisex    2009     1               0.05
12    Boys    2012   630              77.40
37    Boys    2011   164              20.15
33    Boys    2013    11               1.35
9     Boys    2016     8               0.98
6     Boys    2008     1               0.12
39   Girls    2012   476              73.80
11   Girls    2011   145              22.48
21   Girls    2016    15               2.33
2    Girls    2013     5               0.78
31   Girls    2010     2               0.31
30   Girls    2008     1               0.16
35   Girls    2015     1               0.16

    target       feature      n  pct_within_target
21     Men        Casual  15691              75.01
2      Men        Sports   2876              13.75
23     Men        Formal   2193              10.48
6      Men        Ethnic     90               0.43
10     Men  Smart Casual     44               0.21
16     Men       Missing     23               0.11
26     Men        Travel      1               0.00
3    Women        Casual  10774              76.09
24   Women        Ethnic   2462              17.39
22   Women        Sports    759               5.36
4    Women        Formal    106               0.75
14   Women       Missing     31               0.22
20   Women         Party     13               0.09
1    Women  Smart Casual     11               0.08
17   Women        Travel      4               0.03
12  Unisex        Casual   1758              84.52
15  Unisex        Sports    282              13.56
8   Unisex        Travel     20               0.96
5   Unisex       Missing     18               0.87
7   Unisex          Home      1               0.05
13  Unisex        Formal      1               0.05
25    Boys        Casual    783              96.19
18    Boys        Sports     21               2.58
19    Boys        Ethnic     10               1.23
0    Girls        Casual    635              98.45
11   Girls        Ethnic      8               1.24
9    Girls        Sports      2               0.31

### Target: `occasion`

`occasion` is `usage` in the raw CSV (Casual, Sports, Ethnic, Formal, …).  
Compared with `gender`, `masterCategory`, `subCategory`, `articleType`, `baseColour`, `season`, `year`.

In [16]:
occasion_partners = [c for c in FEATURE_COLS if c != "occasion"]
print("Cramér's V vs occasion")
display(
    pd.Series({c: cramers_v(df["occasion"], df[c]) for c in occasion_partners}, name="cramers_v")
    .sort_values(ascending=False)
    .to_frame()
)

for feature in occasion_partners:
    top_n = 12 if df[feature].nunique(dropna=False) > 12 else 30
    display(plot_bivariate("occasion", feature, top_n_feature=top_n))

Cramér's V vs occasion

                cramers_v
articleType      0.659644
subCategory      0.465527
masterCategory   0.434160
gender           0.207088
baseColour       0.152567
year             0.137203
season           0.135154

          target feature      n  pct_within_target
10        Casual     Men  15691              52.94
3         Casual   Women  10774              36.35
2         Casual  Unisex   1758               5.93
17        Casual    Boys    783               2.64
21        Casual   Girls    635               2.14
8         Sports     Men   2876              72.99
25        Sports   Women    759              19.26
24        Sports  Unisex    282               7.16
7         Sports    Boys     21               0.53
19        Sports   Girls      2               0.05
5         Ethnic   Women   2462              95.80
13        Ethnic     Men     90               3.50
18        Ethnic    Boys     10               0.39
23        Ethnic   Girls      8               0.31
4         Formal     Men   2193              95.35
12        Formal   Women    106               4.61
14        Formal  Unisex      1               0.04
1        Missing   Women     31              43.06
26       Missing     Men     23              31.94
0        Missing  Unisex     18              25.00
11  Smart Casual     Men     44              80.00
6   Smart Casual   Women     11              20.00
15        Travel  Unisex     20              80.00
16        Travel   Women      4              16.00
22        Travel     Men      1               4.00
9          Party   Women     13             100.00
20          Home  Unisex      1             100.00

          target         feature      n  pct_within_target
2         Casual         Apparel  14045              47.38
11        Casual     Accessories   8677              29.27
3         Casual        Footwear   5890              19.87
8         Casual   Personal Care    967               3.26
30        Casual      Free Items     58               0.20
0         Casual  Sporting Goods      4               0.01
24        Sports        Footwear   1993              50.58
23        Sports         Apparel   1584              40.20
17        Sports     Accessories    341               8.65
33        Sports  Sporting Goods     21               0.53
22        Sports      Free Items      1               0.03
6         Ethnic         Apparel   2336              90.89
12        Ethnic     Accessories    199               7.74
5         Ethnic        Footwear     17               0.66
31        Ethnic      Free Items     17               0.66
10        Ethnic   Personal Care      1               0.04
19        Formal         Apparel   1152              50.09
18        Formal        Footwear    621              27.00
25        Formal     Accessories    521              22.65
32        Formal      Free Items      6               0.26
29       Missing   Personal Care     32              44.44
21       Missing     Accessories     28              38.89
28       Missing         Apparel     10              13.89
27       Missing        Footwear      2               2.78
13  Smart Casual     Accessories     26              47.27
4   Smart Casual        Footwear     17              30.91
7   Smart Casual         Apparel     12              21.82
26        Travel     Accessories     25             100.00
14         Party         Apparel      8              61.54
9          Party     Accessories      2              15.38
1          Party      Free Items      1               7.69
15         Party   Personal Care      1               7.69
16         Party        Footwear      1               7.69
20          Home            Home      1             100.00

          target     feature      n  pct_within_target
25        Casual     Topwear  10450              35.26
50        Casual       Shoes   4134              13.95
18        Casual        Bags   2524               8.52
35        Casual       Other   2188               7.38
37        Casual     Watches   2163               7.30
2         Casual  Bottomwear   1670               5.63
48        Casual   Innerwear   1382               4.66
47        Casual     Eyewear   1039               3.51
23        Casual      Sandal    901               3.04
21        Casual   Fragrance    887               2.99
31        Casual  Flip Flops    855               2.88
8         Casual     Wallets    785               2.65
26        Casual       Belts    663               2.24
30        Sports       Shoes   1972              50.05
20        Sports     Topwear   1079              27.39
36        Sports  Bottomwear    462              11.73
0         Sports       Other    238               6.04
10        Sports        Bags     92               2.34
4         Sports     Watches     49               1.24
43        Sports   Innerwear     19               0.48
7         Sports      Sandal     14               0.36
44        Sports     Eyewear      8               0.20
51        Sports  Flip Flops      7               0.18
27        Ethnic     Topwear   1962              76.34
38        Ethnic       Other    443              17.24
5         Ethnic  Bottomwear    143               5.56
53        Ethnic       Shoes     17               0.66
19        Ethnic        Bags      4               0.16
22        Ethnic   Fragrance      1               0.04
12        Formal     Topwear    904              39.30
3         Formal       Shoes    612              26.61
33        Formal       Other    349              15.17
54        Formal  Bottomwear    247              10.74
13        Formal       Belts    129               5.61
49        Formal     Wallets     30               1.30
32        Formal     Watches     18               0.78
42        Formal      Sandal      9               0.39
58        Formal        Bags      2               0.09
45       Missing       Other     45              62.50
34       Missing   Fragrance     10              13.89
16       Missing     Wallets      8              11.11
56       Missing     Topwear      3               4.17
11       Missing   Innerwear      2               2.78
15       Missing  Bottomwear      2               2.78
59       Missing      Sandal      2               2.78
39  Smart Casual     Watches     21              38.18
52  Smart Casual       Shoes     16              29.09
28  Smart Casual     Topwear     10              18.18
9   Smart Casual     Wallets      3               5.45
6   Smart Casual  Bottomwear      2               3.64
24  Smart Casual      Sandal      1               1.82
29  Smart Casual       Belts      1               1.82
41  Smart Casual       Other      1               1.82
1         Travel        Bags     25             100.00
55         Party       Other      8              61.54
14         Party   Fragrance      1               7.69
17         Party        Bags      1               7.69
40         Party       Shoes      1               7.69
46         Party     Topwear      1               7.69
57         Party     Watches      1               7.69
60          Home       Other      1             100.00

          target       feature      n  pct_within_target
2         Casual         Other  10003              33.75
3         Casual       Tshirts   5829              19.67
10        Casual  Casual Shoes   2661               8.98
24        Casual        Shirts   2213               7.47
5         Casual       Watches   2163               7.30
17        Casual          Tops   1554               5.24
36        Casual      Handbags   1426               4.81
1         Casual    Sunglasses   1039               3.51
42        Casual         Heels   1017               3.43
11        Casual    Flip Flops    856               2.89
23        Casual       Sandals    842               2.84
14        Casual  Sports Shoes     33               0.11
26        Casual        Kurtas      5               0.02
49        Sports  Sports Shoes   1958              49.70
33        Sports       Tshirts    950              24.11
34        Sports         Other    927              23.53
35        Sports       Watches     49               1.24
22        Sports          Tops     12               0.30
51        Sports  Casual Shoes     12               0.30
48        Sports       Sandals     11               0.28
40        Sports    Sunglasses      8               0.20
50        Sports    Flip Flops      7               0.18
41        Sports      Handbags      6               0.15
25        Ethnic        Kurtas   1551              60.35
6         Ethnic         Other    953              37.08
18        Ethnic          Tops     45               1.75
28        Ethnic        Shirts     13               0.51
44        Ethnic         Heels      7               0.27
37        Ethnic      Handbags      1               0.04
12        Formal         Other   1392              60.52
39        Formal        Shirts    850              36.96
9         Formal         Heels     22               0.96
16        Formal       Watches     18               0.78
38        Formal       Sandals      9               0.39
7         Formal  Casual Shoes      4               0.17
13        Formal       Tshirts      2               0.09
46        Formal          Tops      2               0.09
30        Formal      Handbags      1               0.04
31       Missing         Other     67              93.06
20       Missing        Shirts      3               4.17
19       Missing       Sandals      2               2.78
8   Smart Casual       Watches     21              38.18
4   Smart Casual         Other     16              29.09
27  Smart Casual        Shirts     10              18.18
15  Smart Casual  Casual Shoes      6              10.91
29  Smart Casual       Sandals      1               1.82
43  Smart Casual         Heels      1               1.82
21        Travel         Other     20              80.00
0         Travel      Handbags      5              20.00
52         Party         Other     10              76.92
32         Party         Heels      1               7.69
45         Party          Tops      1               7.69
53         Party       Watches      1               7.69
47          Home         Other      1             100.00

    target feature     n  pct_within_target
45  Casual   Black  6660              22.47
38  Casual   Other  3739              12.61
27  Casual    Blue  3461              11.68
7   Casual   White  3369              11.37
55  Casual   Brown  2455               8.28
..     ...     ...   ...                ...
10  Travel    Pink     1               4.00
67   Party   Black     7              53.85
61   Party   Other     4              30.77
71   Party  Silver     2              15.38
62    Home  Yellow     1             100.00

[82 rows x 4 columns]

          target  feature      n  pct_within_target
1         Casual   Summer  14351              48.42
19        Casual     Fall   7037              23.74
8         Casual   Winter   6882              23.22
23        Casual   Spring   1371               4.63
18        Sports   Summer   2081              52.82
0         Sports     Fall   1617              41.04
6         Sports   Winter    113               2.87
30        Sports   Spring    109               2.77
16        Sports  Missing     20               0.51
3         Ethnic   Summer   1612              62.72
21        Ethnic     Fall    862              33.54
9         Ethnic   Winter     92               3.58
25        Ethnic   Spring      4               0.16
12        Formal   Summer   1048              45.57
31        Formal     Fall    970              42.17
22        Formal   Winter    245              10.65
17        Formal   Spring     37               1.61
11       Missing   Spring     39              54.17
5        Missing   Summer     19              26.39
28       Missing     Fall     11              15.28
24       Missing   Winter      3               4.17
10  Smart Casual   Winter     30              54.55
20  Smart Casual     Fall     13              23.64
2   Smart Casual   Summer      9              16.36
26  Smart Casual   Spring      3               5.45
4         Travel   Winter     12              48.00
15        Travel   Summer     11              44.00
13        Travel   Spring      2               8.00
32         Party   Summer      6              46.15
29         Party   Winter      4              30.77
7          Party   Spring      2              15.38
14         Party     Fall      1               7.69
27          Home     Fall      1             100.00

          target feature     n  pct_within_target
48        Casual    2012  9744              32.87
4         Casual    2011  9551              32.22
44        Casual    2016  5131              17.31
11        Casual    2015  2226               7.51
52        Casual    2017  1292               4.36
62        Casual    2013   859               2.90
30        Casual    2010   394               1.33
25        Casual    2018   281               0.95
14        Casual    2014   143               0.48
31        Casual    2009    16               0.05
40        Casual    2008     3               0.01
38        Casual    2007     1               0.00
58        Sports    2011  2175              55.20
24        Sports    2012  1102              27.97
21        Sports    2010   403              10.23
10        Sports    2013   106               2.69
42        Sports    2016    76               1.93
60        Sports    2015    30               0.76
61        Sports    2014    26               0.66
18        Sports    2017     9               0.23
51        Sports    2018     6               0.15
23        Sports    2009     4               0.10
56        Sports    2008     2               0.05
0         Sports    2007     1               0.03
50        Ethnic    2012  1597              62.14
7         Ethnic    2011   888              34.55
46        Ethnic    2016    68               2.65
12        Ethnic    2015    11               0.43
35        Ethnic    2010     2               0.08
63        Ethnic    2013     2               0.08
27        Ethnic    2018     1               0.04
54        Ethnic    2017     1               0.04
13        Formal    2011  1039              45.17
22        Formal    2012   885              38.48
59        Formal    2013   140               6.09
32        Formal    2018    98               4.26
5         Formal    2015    65               2.83
36        Formal    2016    62               2.70
26        Formal    2010     5               0.22
8         Formal    2014     4               0.17
20        Formal    2008     1               0.04
57        Formal    2017     1               0.04
29       Missing    2017    35              48.61
45       Missing    2011    18              25.00
2        Missing    2013     7               9.72
19       Missing    2012     7               9.72
9        Missing    2016     2               2.78
37       Missing    2015     2               2.78
53       Missing    2018     1               1.39
47  Smart Casual    2016    21              38.18
49  Smart Casual    2012    19              34.55
6   Smart Casual    2011     6              10.91
28  Smart Casual    2018     4               7.27
64  Smart Casual    2013     2               3.64
16  Smart Casual    2014     1               1.82
33  Smart Casual    2010     1               1.82
55  Smart Casual    2017     1               1.82
39        Travel    2015    14              56.00
17        Travel    2011     9              36.00
15        Travel    2008     1               4.00
43        Travel    2018     1               4.00
34         Party    2012     6              46.15
1          Party    2016     3              23.08
65         Party    2011     3              23.08
41         Party    2017     1               7.69
3           Home    2012     1             100.00

## Quick DuckDB snapshots

In [17]:
print("Top subCategory × occasion cells")
display(
    con.sql(
        """
        SELECT subCategory, occasion, COUNT(*) AS n
        FROM styles
        GROUP BY 1, 2
        ORDER BY n DESC
        LIMIT 15
        """
    ).df()
)

print("Gender mix within masterCategory")
display(
    con.sql(
        """
        SELECT
            masterCategory,
            gender,
            COUNT(*) AS n,
            ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (PARTITION BY masterCategory), 1) AS pct_within_master
        FROM styles
        GROUP BY 1, 2
        ORDER BY masterCategory, n DESC
        """
    ).df()
)

print("Season mix by year")
display(
    con.sql(
        """
        SELECT
            year,
            COALESCE(CAST(season AS VARCHAR), 'Missing') AS season,
            COUNT(*) AS n
        FROM styles
        GROUP BY 1, 2
        ORDER BY year, n DESC
        """
    ).df()
)

Top subCategory × occasion cells

   subCategory occasion      n
0      Topwear   Casual  10450
1        Shoes   Casual   4134
2         Bags   Casual   2524
3      Watches   Casual   2163
4        Shoes   Sports   1972
5      Topwear   Ethnic   1962
6   Bottomwear   Casual   1670
7    Innerwear   Casual   1382
8      Topwear   Sports   1079
9      Eyewear   Casual   1039
10     Topwear   Formal    904
11      Sandal   Casual    901
12   Fragrance   Casual    887
13  Flip Flops   Casual    855
14     Wallets   Casual    785

Gender mix within masterCategory

    masterCategory  gender      n  pct_within_master
0      Accessories   Women   4334               44.1
1      Accessories     Men   3994               40.7
2      Accessories  Unisex   1447               14.7
3      Accessories   Girls     27                0.3
4      Accessories    Boys     17                0.2
5          Apparel     Men  10875               56.8
6          Apparel   Women   6886               36.0
7          Apparel    Boys    743                3.9
8          Apparel   Girls    558                2.9
9          Apparel  Unisex     85                0.4
10        Footwear     Men   5480               64.2
11        Footwear   Women   2440               28.6
12        Footwear  Unisex    507                5.9
13        Footwear   Girls     60                0.7
14        Footwear    Boys     54                0.6
15      Free Items     Men     42               50.6
16      Free Items   Women     38               45.8
17      Free Items  Unisex      3                3.6
18            Home  Unisex      1              100.0
19   Personal Care     Men    527               52.6
20   Personal Care   Women    462               46.2
21   Personal Care  Unisex     12                1.2
22  Sporting Goods  Unisex     25              100.0

Season mix by year

    year   season      n
0   2007   Spring      2
1   2008   Spring      3
2   2008   Summer      2
3   2008   Winter      1
4   2008     Fall      1
5   2009     Fall     19
6   2009   Summer      1
7   2010     Fall    638
8   2010   Summer     94
9   2010   Winter     70
10  2010   Spring      3
11  2011     Fall   8749
12  2011   Summer   4683
13  2011   Winter    157
14  2011   Spring     80
15  2011  Missing     20
16  2012   Summer  11423
17  2012     Fall    964
18  2012   Winter    862
19  2012   Spring    112
20  2013   Summer    648
21  2013   Spring    353
22  2013     Fall     66
23  2013   Winter     49
24  2014   Summer     86
25  2014   Winter     45
26  2014     Fall     30
27  2014   Spring     13
28  2015   Winter   2071
29  2015   Summer    247
30  2015     Fall     28
31  2015   Spring      2
32  2016   Winter   3782
33  2016   Summer   1570
34  2016     Fall     11
35  2017   Spring    998
36  2017   Summer    337
37  2017   Winter      5
38  2018   Winter    339
39  2018   Summer     46
40  2018     Fall      6
41  2018   Spring      1

# Conclusion

Dataset Overview

  - 38,617 rows, each with a unique id — no duplicates
  - 10 columns after cleaning: id, gender, masterCategory, subCategory, articleType, baseColour, season, year, occasion (renamed from usage), productDisplayName
  - Very clean: missing values are negligible — occasion has the most at just 0.19% (72 rows), season 0.05%, baseColour 0.04%

Class Imbalance (key concern for modeling)
| Feature | Dominant class | % | Tail classes |                                                                                                                                    
  | --- | --- | --- | --- |                                                                                                                                                          
  | gender | Men (54%) + Women (37%) | 91% | Boys/Girls/Unisex are tiny minorities |                                                                                                 
  | masterCategory | Apparel (50%) + Accessories (25%) + Footwear (22%) | 97% | Personal Care, Free Items, Sporting Goods, Home are negligible |                                     
  | subCategory | Topwear alone = 37%; top 5 cover ~74% | — | Long tail of 41 categories, many very small |                                                                        
  | season | Summer (50%) + Fall (27%) | 77% | Spring is only 4% |                                                                                                                   
  | occasion | Casual dominates at 77% | — | Sports 10%, Ethnic 7%, Formal 6%; Smart Casual/Travel/Party/Home are near-zero |                                                      
  | year | 2011-2012 account for ~70% of data | — | Very uneven temporal sampling (2007-2009 have <30 rows) |                                                                        
  | baseColour | Black (23%), White (13%), Blue (12%) | 48% | 46 colours total, long tail |   

Feature Associations (Cramer's V)

  The key finding from the association matrix:
| Feature pair | Cramér's V | Interpretation |                                                                                                                                     
  | --- | --- | --- |
  | masterCategory ↔ subCategory | 0.999 | Near-perfect — subCategory is essentially a finer split of masterCategory (hierarchical/redundant) |
  | articleType ↔ subCategory | 0.959 | Also near-redundant — articleType further refines subCategory |
  | articleType ↔ occasion | 0.660 | Strong — article type strongly predicts usage context |
  | year ↔ season | 0.601 | Moderate — different years have different season distributions (data collection artifact) |
  | articleType ↔ season | 0.563 | Moderate — some product types are seasonal |
  | articleType ↔ gender | 0.515 | Moderate — gendered product assortments differ |
  | masterCategory ↔ season/occasion | ~0.43–0.47 | Moderate |
  | baseColour | ≤0.21 with all targets | Weak — colour is relatively independent of other attributes |

Key Takeaways for Modeling

  1. Hierarchical redundancy: masterCategory → subCategory → articleType form a near-deterministic hierarchy. Using all three as features would introduce multicollinearity. Pick one
   level or encode the hierarchy.
  2. Severe class imbalance on all targets, especially occasion (77% Casual). Models will need stratified sampling, class weights, or oversampling for minority classes.
  3. baseColour is the most independent feature — it carries unique signal not captured by category/type, making it potentially valuable as a complementary feature.
  4. Temporal bias: The dataset is concentrated in 2011-2012 (~70%). Year-based features or splits need care — year ↔ season correlation is likely a collection artifact, not a real
  fashion trend signal.
  5. Tiny/rare classes (Home, Smart Casual, Travel, Party, Sporting Goods) may need to be merged or dropped depending on the task.
  6. Missing data is not a problem — all columns have <0.2% missing, so simple imputation or dropping is fine.